language: generic
dist: trusty

sudo: true
services:
  - docker

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env: >
        TARGET=x86_64-apple-darwin
    - os: osx
      osx_image: xcode8
      env: >
        TARGET=i686-apple-darwin

script:
  - ./build

deploy:
  - provider: s3
    access_key_id: AKIAJE27ZGMR45IXA6OA
    secret_access_key: ${S3_KEY}
    bucket: record-query
    region: eu-west-1
    skip_cleanup: true
    local_dir: target/upload
    upload-dir: v8
    on:
      repo: dflemstr/v8-static
