language: generic
dist: trusty

sudo: true
services:
  - docker

matrix:
  include:
    - os: linux
      env: >
        TARGET=x86_64-unknown-linux-gnu
        GN_ARGS='target_os="linux" target_cpu="x64"'
        USE_DOCKER=true
    - os: linux
      env: >
        TARGET=x86_64-unknown-linux-musl
        GN_ARGS='target_os="linux" target_cpu="x64" custom_toolchain="//build/toolchain/linux:x64_musl" v8_snapshot_toolchain="//build/toolchain/linux:x64"'
        USE_DOCKER=true
    - os: linux
      env: >
        TARGET=i686-unknown-linux-gnu
        GN_ARGS='target_os="linux" target_cpu="x86"'
        USE_DOCKER=true
    - os: linux
      env: >
        TARGET=i686-unknown-linux-musl
        GN_ARGS='target_os="linux" target_cpu="x86" custom_toolchain="//build/toolchain/linux:x86_musl" v8_snapshot_toolchain="//build/toolchain/linux:x86"'
        USE_DOCKER=true
    - os: linux
      env: >
        TARGET=armv7-unknown-linux-gnueabihf
        GN_ARGS='target_os="linux" target_cpu="arm" arm_version=7 arm_float_abi="hard"'
        USE_DOCKER=true
    - os: linux
      env: >
        TARGET=armv7-unknown-linux-musleabihf
        GN_ARGS='target_os="linux" target_cpu="arm" arm_version=7 arm_float_abi="hard" custom_toolchain="//build/toolchain/linux:arm_musl" v8_snapshot_toolchain="//build/toolchain/linux:x86"'
        USE_DOCKER=true
    - os: osx
      osx_image: xcode8
      env: >
        TARGET=x86_64-apple-darwin
        GN_ARGS='target_os="mac" target_cpu="x64"'
    - os: osx
      osx_image: xcode8
      env: >
        TARGET=i686-apple-darwin
        GN_ARGS='target_os="mac" target_cpu="x86"'

script:
  - set -e

deploy:
  - provider: s3
    access_key_id: AKIAJE27ZGMR45IXA6OA
    secret_access_key: ${S3_KEY}
    bucket: record-query
    region: eu-west-1
    skip_cleanup: true
    local_dir: upload
    upload-dir: v8
    on:
      repo: dflemstr/v8-static
