#!/bin/bash -eux

srcdir=$PWD

mkdir -p target
cd target

fetch-depot-tools() {
    if [ -d depot_tools ]
    then (cd depot_tools; git pull)
    else git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    fi

    PATH=$PWD/depot_tools:$PATH
    export PATH
}

fetch-v8() {
    if [ -d v8 ]
    then
        pushd v8

        if [ -f BUILD.gn.orig ]
        then mv BUILD.gn.orig BUILD.gn
        fi

        if [ -f build/toolchain/linux/BUILD.gn.orig ]
        then mv build/toolchain/linux/BUILD.gn.orig build/toolchain/linux/BUILD.gn
        fi

        popd
    else
        fetch v8
    fi

    pushd v8
    gclient sync --revision 5.6.222

    cp BUILD.gn BUILD.gn.orig
    cat "$srcdir/extra.gn" >> BUILD.gn
    cp build/toolchain/linux/BUILD.gn build/toolchain/linux/BUILD.gn.orig
    cat "$srcdir/extra-toolchain-linux.gn" >> build/toolchain/linux/BUILD.gn

    popd
}

run-docker() {
    docker pull "dflemstr/buildenv:$TARGET"
    exec docker run \
         --rm -ti \
         --entrypoint /bin/bash \
         -v "$srcdir:/host" \
         -e "TARGET=$TARGET" \
         -e "USE_DOCKER=false" \
         -e "IN_DOCKER=true" \
         "dflemstr/buildenv:$TARGET" \
         -c "if ! getent group $(id -gn); then groupadd -g $(id -g) $(id -gn); fi &&
             if ! getent passwd $(id -un); then useradd -u $(id -u) -g $(id -g) -m $(id -un); fi &&
             echo '$(id -un) ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
             cd /host &&
             sudo -HEu $(id -un) ./build"
}

run-gn() {
    default_gn_args=(
        'is_component_build=false'
        'is_debug=false'
        'is_official_build=true'
        'optimize_for_size=true'
        'v8_use_snapshot=true'
        'v8_use_external_startup_data=false'
        'v8_enable_i18n_support=true'
        'is_clang=false'
        'use_sysroot=false'
    )
    pushd v8
    gn gen "out/$TARGET" --args="${default_gn_args[*]} $(cat "$srcdir/args/$TARGET.args")"
    popd
}

build-v8() {
    ninja -C "v8/out/$TARGET" v8uber
}

prepare-upload() {
    rm -rf v8-build
    mkdir v8-build
    mkdir v8-build/include
    mv v8/include/* "v8-build/include"
    mkdir v8-build/lib
    mv "v8/out/$TARGET/obj/libv8uber.a" v8-build/lib
    tar -cvzf v8-build.tar.gz v8-build
    UPLOAD_DIR=upload/$TARGET/$(cd v8; git describe --always --tags)
    mkdir -p "$UPLOAD_DIR"
    mv v8-build.tar.gz "$UPLOAD_DIR"
}

if [ "${IN_DOCKER:-false}" = true ]
then
    sudo apt-get update
    sudo apt-get install -y \
         git python build-essential libglib2.0-dev gcc-multilib g++-multilib
    sudo rm -rf /var/lib/apt/lists/*
fi

if [ "${USE_DOCKER:-false}" = true ]
then
    run-docker
fi

fetch-depot-tools
fetch-v8
run-gn
build-v8
prepare-upload
